# Generated by Django 2.2.2 on 2019-06-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myprojectsmodel',
            table='my_projects',
        ),
    ]
