# Generated by Django 2.2.2 on 2019-06-12 21:56

from django.db import migrations, models
import myfolder_section.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder_section', '0002_auto_20190612_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojectsmodel',
            name='project_name',
            field=models.CharField(max_length=150, unique=True, validators=[myfolder_section.validators.clean_project_name]),
        ),
    ]
