# Generated by Django 2.2.2 on 2019-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder_section', '0004_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.IntegerField(default=0),
        ),
    ]
