# Generated by Django 2.2.2 on 2019-06-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder_section', '0006_filemodel_filesearchtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesearchtags',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myfolder_section.FileModel'),
            preserve_default=False,
        ),
    ]
